server:
  port: 9090
###### dubbo #####
dubbo:
  application:
    id: member-service
    name: member-service
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.kano.member.provider
  protocol:
    name: dubbo
    port: 10000
