###### http #####
server:
  port: 9090
###### dubbo #####
dubbo:
  application:
    id: member-service-dubbo-provider
    name: member-service-dubbo-provider
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.soranico.member.service
  protocol:
    name: dubbo
    port: 10000
###### log #####
spring:
  application:
    name: member-service-dubbo-provider
    logger:
      path: log/${spring.application.name}
      level: INFO
