###### http #####
server:
  port: 8000
  tomcat:
    accept-count: 1024
    max-threads: 128
    uri-encoding: UTF-8
    min-spare-threads: 64
###### dubbo #####
dubbo:
  application:
    id: member-manager
    name: member-manager
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    timeout: 8000
###### log #####
spring:
  ##### 注册中心的服务名，如果没有指定 service ######
  application:
    name: member-manager
  ##### 注册中心配置 ######
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    ##### 日志 ######
    logger:
      path: log/
      level: DEBUG
kano:
  http:
    method:
      enable: true
