server:
  port: 7000
spring:
  cloud:
    ##### nacos #####
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      ##### route #####
      routes:
        - id: member-manager
          uri: lb://member-manager
          predicates:
            - Path=/v1/member/**
  application:
    name: kano-route
    logger:
      path: log/
      level: DEBUG