###### http #####
server:
  port: 6000
###### dubbo #####
dubbo:
  application:
    id: security-manager
    name: security-manager
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    timeout: 8000
###### log #####
spring:
  ##### 注册中心的服务名，如果没有指定 service ######
  application:
    name: security-manager
  ##### 注册中心配置 ######
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    ##### 日志 ######
    logger:
      level: DEBUG
kano:
  sercurity
